workspace = { members = ["crates/*"] }
[package]
name = "codeforces"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
